#~~~Data input
print("Data input")
laukiantys <- read.csv(file="data/laukianciuju_eileje_ataskaita.csv",sep = ";",encoding="UTF-8",na.strings=c("","NA"))
darzeliai <- read.csv(file="data/darzeliai.csv",encoding="UTF-8",na.strings=c("","NA"))
grupes <- read.csv(file="data/grupes.csv",encoding="UTF-8",na.strings=c("","NA"))
istaigos <- read.csv(file="data/istaigos.csv",sep = ";", encoding="UTF-8",na.strings=c("","NA"))
vaikai_grup <- read.csv(file="data/lankanciu_vaiku_ataskaita_pagal_grupes.csv",sep = ";", encoding="UTF-8",na.strings=c("","NA"))
lankomumas <- read.csv(file="data/lankomumo_ziniarasciai_2016-07-01-2016-07-31.csv",sep = ";", encoding="UTF-8",na.strings=c("","NA"))
prasymai <- read.csv(file="data/visi_prasymai.csv", encoding="UTF-8",na.strings=c("","NA"))
print("Data input done")